config/routes.rb
Rails.application.routes.draw do
    get 'issues/show'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'page#welcome' 
	get '/about' => 'page#about'
	#issues
	get '/issues/new' => 'issues#new'
	get '/issues/:id' => "issues#show", :as => "issue"
	delete 'issues/:id' => 'issues#destroy'
	get 'issues' => 'issues#index', :as => 'issues'
	post 'issues' => 'issues#create'
	get 'issues/:id/edit' => 'issues#edit', :as => 'edit_issue'
	patch 'issues/:id' => 'issues#update'

	#comments
	resources :comments, only: [:create]

	#users
	get 'signup' => 'users#signup', :as =>'signup'
	post 'signup' => 'users#create', :as => 'signup_create'
	get 'login' => 'users#login', :as => 'login'
	post 'login_create' => 'users#login_create'
	delete 'logout' => 'users#logout', :as => 'logout'
	delete 'delete/:id' => 'users#destroy', :as => 'delete'
	get 'show' => 'users#index', :as => 'show'
	get 'users/:id/edit' => 'users#edit', :as => 'edit_user'
	patch 'users/:id' => 'users#update', :as => 'update_user'
	get 'show_user' => 'users#show_user', :as => 'show_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :issue
	belongs_to :user

end

app/models/issue.rb
class Issue < ActiveRecord::Base
	has_many :comments
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :comments
	has_many :issues
	before_create { generate_token(:auth_token)}
	validates :name, :email, presence: true
	validates :name, :email, uniqueness: { case_sensitive: false }
	def generate_token(colum)
		begin
			self[colum] = SecureRandom.urlsafe_base64
		end while User.exists?(colum => self[colum])
	end

	def avatar
	  gravatar_id = Digest::MD5.hexdigest(self.email.downcase)
	  "http://gravatar.com/avatar/#{gravatar_id}.png?s=512&d=retro"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	#获取当前用户
	def current_user
  		@current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
	end
	helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	#创建留言
	def create
	  @comment = Comment.new(comment_params)
	  @comment.save
	  respond_to do |format|
	  	format.js
	  end
	end

	private
	  def comment_params
	  	params.require(:comment).permit(:issue_id, :user_id, :content)
	  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  #展示活动以及活动评论
  def show
  	   @issue = Issue.find(params[:id])
       @comments = @issue.comments
  end
  #删除活动
  #跳转主页面
  def destroy
	  issue = Issue.find(params[:id])
	  issue.destroy
    flash[:notice] = "活动删除成功"
	  redirect_to :root
  end
  #活动创建页面
  def new
    if not current_user
      flash[:notice] = "请先登录"
      redirect_to :root
      return
    else
      @issue = Issue.new
    end
  end
  #创建活动
  def create
  	Issue.create(issue_params)
  	redirect_to :root
  end
  #编辑活动界面
  def edit
  	@issue = Issue.find(params[:id])
  end
  #修改活动
  def update
	  i = Issue.find(params[:id])
	  i.update_attributes(issue_params)
	  redirect_to :root
  end
  private
	  def issue_params
	    params.require(:issue).permit(:title, :content, :user_id)
	  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  #主页面
  def welcome
  	 #把所有活动通过创建时间排序
  	 @issues  = Issue.all.reverse
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #注册界面
  def signup
  	@user = User.new
  end
  #展示所有用户
  def index
    if not current_user && current_user.admin == "true"
      flash[:notice] = "请用管理员用户登录"
      redirect_to :login
      return
    else
      @users = User.all
    end
  end
  #注册
  #cookies用于标识用户状态
  def create
  	@user = User.new(user_params)
  	if @user.save
  		cookies[:auth_token] = @user.auth_token
  		redirect_to :root
  	else
  		render :signup
  	end
  end
  #登陆界面
  def login
  	@user = User.new
  end
  #登陆
  def login_create
  	user = User.find_by_name(params[:name])
  	if user && user.authenticate(params[:password])
	    if params[:remember_me]
	    	cookies.permanent[:auth_token] = user.auth_token
	    else
	    	cookies[:auth_token] = user.auth_token
	    end
	    flash.notice = "登陆成功"
	    redirect_to :root
  	else
  		flash.notice = "用户名或密码输入错误"
    	redirect_to :login
  	end
  end
  #编辑用户界面
  def edit
    @user = User.find(params[:id])
  end
  #更新用户
  def update
    u = User.find(params[:id])
    u.update_attributes(user_params)
    flash.notice = "修改用户成功"
    redirect_to :show
  end
  #登出
  def logout
  	cookies.delete(:auth_token)
  	redirect_to :root
  end
  #删除用户(注：管理员才可以)
  def destroy
    user = User.find(params[:id])
    user.destroy
    flash.notice = "用户删除成功"
    redirect_to :show
  end
  #用户主页
  def show_user
    if current_user
      @current_user = current_user
    else
      redirect_to :root
    end
  end
  private
  	def user_params
  		params.require(:user).permit!
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
  	def block_code(code, language)
    	Pygments.highlight(code, lexer: language)
  	end
  end
	def markdown(text)
	  renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
	  options = {
	    autolink: true,
	    no_intra_emphasis: true,
	    fenced_code_blocks: true,
	    lax_html_blocks: true,
	    strikethrough: true,
	    superscript: true
	  }
	  Redcarpet::Markdown.new(renderer, options).render(text).html_safe
	end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/comments/create.js.erb
$(".replies").append("<%= j render(partial: 'shared/comment', locals: {c: @comment}) %>");
$(".reply textarea").val('');

app/views/issues/edit.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for @issue do |f| %>
      <dl class="form">
        <dt><%= f.label :标题 %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :活动内容 %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <p><%= f.submit "更新活动", :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/issues/new.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for (Issue.new(user_id: current_user.id)) do |f| %>
      <%= f.hidden_field :user_id %>
      <dl class="form">
        <dt><%= f.label "标题" %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label "活动内容" %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <p><%= f.submit "发布新活动", :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/issues/show.html.erb
<div class="issue-heading">
  <div class="container">
    <%= @issue.title %>
    <% if current_user && current_user == @issue.user%>
      <%= link_to '删除活动', issue_path(@issue), method: :delete, data: {confirm: "确定要删除吗？" }, class: "btn btn-primary" %>
      <%= link_to '修改活动', edit_issue_path(@issue), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="replies">
    <article class="reply clearfix">
      <div class="avatar">
       <%= image_tag @issue.user.avatar, class: "image-circle" %>
      </div>
      <div class="body">
        <div class="heading">
          <h5 class="name"><%= link_to @issue.user.name,"#"%></h5>
        </div>
        <%= markdown @issue.content %>
      </div>
    </article>
    <% @comments.each do |c|%>
      <%= render partial: 'shared/comment', locals:{c: c} %>
    <% end %>
  </div>
  <% if current_user %>
    <%= render partial: 'shared/comment_box', locals: {issue: @issue} %>
  <% else %>
    <%= link_to "请先登录", login_path ,class: "btn btn-primary"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>BBS</title>
  <link rel="stylesheet" href="<%= stylesheet_path 'application' %>">
  <%= javascript_include_tag "application"%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] + '-' + params[:action] %>">  
  <div class="navbar clearfix">
    <div class="container">
        <a class="navbar-brand" href="/">BBS</a>
        <ul class="nav left">
            <li><%= link_to t("navbar.about"),'about'%></li>
          <% if current_user && current_user.admin == "true" %>
            <li><%= link_to "所有用户",'show'%></a></li>
          <% end %>
        </ul>
        <ul class="nav right">
          <% if current_user %>
            <li><%= link_to current_user.name, show_user_path %></li>
            <li><%= link_to "退出", logout_path, method: 'delete' %></li>
          <% else %>
            <li><%= link_to "登陆", login_path %></li>
            <li><%= link_to "注册", signup_path %></li>
          <% end %>
         </ul>
      </div>
  </div>
  <% if flash.notice %>
    <div class="notice">
      <%= flash.notice %>
    </div>
  <% end %>
  <%= yield %>
  <%= render 'shared/footer'%>
  
</body>
</html>

app/views/page/about.html.erb
<div class="container">
  <div class="">
  	<p>这是一个慕课网学习项目</p>
  </div>
</div>

app/views/page/welcome.html.erb
 <div class="home-banner" data-stretch="<%= image_url "bj.jpg" %>">
 	<div class="banner-inner container clearfix">
		<h1>It's Party Time Drinkup!</h1>
		<p class="subheading">你好用户~</p>
		<div class="home-banner-links">
    		<%= link_to "发布新活动", "/issues/new", class: "banner-btn btn" %>
		</div>
	</div>
</div>
<div class="issue-list-header">
	<div class="container clearfix">
		<h1>所有的活动都在下面了....</h1>
	</div>
</div>
<div class="container clearfix">
	<div class="container clearfix">
		<%= render partial: 'shared/issue_list', locals: {issues: @issues} %>
	</div>
</div>
<script>
    $('.home-banner').anystretch();
    var hideNotice = function(){
      $(".notice").fadeOut("slow");
    }
    setTimeout(hideNotice, 2000)
</script>

app/views/shared/_comment.html.erb

    <div class="reply clearfix">
       <div class="avatar">
         <%= link_to '#' do %>
           <%= image_tag c.user.avatar, class: 'image-circle' %>
         <% end %>
       </div>
       <div class="body">
         <div class="heading">
            <h5 class="name"><%= link_to c.user.name, "#" %></h5>
            <span class="datetime">
              <%= time_ago_in_words c.created_at %> 前
            </span>
         </div>
         <%= markdown c.content %>
       </div>
    </div>

app/views/shared/_comment_box.html.erb
<article class="reply clearfix">
  <div class="avatar">
    <%= link_to "#" do %>
      <%= image_tag current_user.avatar, class: "image-circle" %>
    <% end %>
  </div>
  <div class="body">
  <%= form_for(Comment.new(:issue_id => issue.id, :user_id => current_user.id), remote: true) do |f| %>
    <%= f.hidden_field :issue_id %>
    <%= f.hidden_field :user_id  %>
    <%= f.text_area :content %>
    <%= submit_tag '提交评论', class: 'btn btn-primary btn-submit' %>
  <% end %>
  </div>
</article>
<script>
  var commenter_exist = [];
  $('.reply .name a').each(function() {
    if($.inArray($(this).text(), commenter_exist) < 0) {
      commenter_exist.push($(this).text());
    }
  });
  $('textarea').atwho({ at: "@", 'data': commenter_exist });
</script>
<script>
  $(".reply textarea#comment_content").keydown(function(e) {
    if ((e.ctrlKey||e.metaKey) && e.keyCode == 13) {
      $(".reply input[type=submit]").click();
    }
  });
</script>

app/views/shared/_comment_list.html.erb
<% comments.each do |c| %>
    <div class="reply clearfix">
       <div class="avatar">
         <%= link_to '#' do %>
           <%= image_tag c.user.avatar, class: 'image-circle' %>
         <% end %>
       </div>
       <div class="body">
         <div class="heading">
            <h5 class="name"><%= link_to c.user.name, "#" %></h5>
            <span class="datetime">
              <%= time_ago_in_words c.created_at %> 前
            </span>
         </div>
         <%= c.content %>
       </div>
    </div>
  <% end %>

app/views/shared/_footer.html.erb
<div class="footer">
   <div class="container">
   	<a href="https://github.com/tangczc/bbs" class="footer_a">项目源码</a> 
    </div>
</div>

app/views/shared/_issue_list.html.erb
<%issues.each do |i| %>
  <div class="issue-list">
    <article class="issue clearfix">
      <div class="avatar">
        <%= link_to "#" do%>
          <%= image_tag i.user.avatar %>
        <% end %>    
      </div>
      <div class="body">
        <h5 class="title">
          <%= link_to i.title, issue_path(i) %>
        </h5>
        <a class="read-more" href="#">read</a>
        <span class="meta-data">
          <%= link_to i.user.name, "#" %>
          <%= time_ago_in_words(i.created_at) %> 前
        </span>
      </div>
      <div class="issue-comment-count">
           <i class="fa fa-comments icon-muted"></i>
          <%= link_to i.comments.count, i %>
      </div>
    </article>
  </div>
<% end %>

app/views/shared/_show.html.erb
<%users.each do |user| %>
  <table rules=none>
  	<tr>
  		<td><%= image_tag user.avatar, class: 'image_user' %></td>
  		<td><%= link_to user.name, "#" %></td>
  		<td class="setting_btn" colspan="2">
  		  <% if current_user != user %>
  			<%= link_to '删除用户', delete_path(user), method: :delete, data: {confirm: "确定要删除吗？" }, class: "btn btn-primary" %>
  		  <% end %>
  		  <%= link_to "修改用户", edit_user_path(user) ,class: "btn btn-primary" %>
  		</td>	
	</tr>
  </table>
<% end %>

app/views/shared/_userissue_list.html.erb
<%issues.each do |i| %>
  <div class="issue-list">
    <article class="issue clearfix">
      <div class="avatar">
        <%= link_to "#" do%>
          <%= image_tag i.user.avatar %>
        <% end %>    
      </div>
      <div class="body">
        <h5 class="title">
          <%= link_to i.title, issue_path(i) %>
        </h5>
        <%= link_to "read", issue_path(i),class: "read-more" %>     
        <span class="meta-data">
          <%= link_to i.user.name, show_user_path %>
          <%= time_ago_in_words(i.created_at) %> 前
        </span>
      </div>
      <div class="issue-comment-count">
        <%= link_to '删除活动', issue_path(i), method: :delete, data: {confirm: "确定要删除吗？" }, class: "btn btn-primary user_issue_delete", style: "font-size: 18px;" %>
      </div>
    </article>
  </div>
<% end %>

app/views/users/edit.html.erb
  <div class="user_edit">
    <%= form_for @user, url: update_user_path do |f| %>
      <table>
        <tr>
          <td><%= f.label :用户名 %></td>
        </tr>
        <tr>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
            <td><%= f.label :是否添加管理权限? %></td>
        </tr>
        <tr>
          <td>
            <input type="radio" id="post_category1" name="user[admin]" value = true /><span>是</span>      
            <input type="radio" id="post_category2" name="user[admin]" value = false checked="checked" /><span >否</span>
          </td>
        </tr>
      </table>
      <p><input type="submit" class = "submit-issue-button btn btn-primary" ></p>
    <% end %>
  </div> 

app/views/users/index.html.erb
<div class="show_users">
	<%= render partial: 'shared/show', locals: {users: @users} %>
</div>

app/views/users/login.html.erb
<div class="login-form-container clearfix">
  <div class="login-form">
    <%= form_tag  "/login_create" do %>
      <dl class="form">
        <dt>
          <%= label_tag "用户名" %>
        </dt>
        <dd>
          <%= text_field_tag :name, params[:name] %>
        </dd>
      </dl>
      <dl class="form">
        <dt>
          <%= label_tag "密码" %>
        </dt>
        <dd>
          <%= password_field_tag :password, params[:password] %>
        </dd>
      </dl>
      <dl class="form remember-me">
        <%= check_box_tag :remember_me, 1, params[:remember_me] %>
        <%= label_tag "记住我" %>
      </dl>
      <p> <%= submit_tag "登录", :class => "login-button btn btn-primary" %> </p>
      <div class="need-signup">
        <%= link_to "没有账号？注册一个吧", signup_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show_user.html.erb
<div class="information">
	<div class="user_image"><%= image_tag @current_user.avatar, class: 'image_user1' %></div>
	<div class="user_name"><%= @current_user.name %></div>
	<hr/>
	<div class="activity">
		<h3>你所发布的活动都在下面了....</h3>
	</div>
	<div class="user_issue">
		<%= render partial: 'shared/userissue_list', locals: {issues: @current_user.issues} %>
	</div>
</div>

app/views/users/signup.html.erb
<div class="signup-form-container clearfix ">
  <div class="signup-form">
	<%= form_for @user ,url: signup_create_path do |f|%>
	  <dl class="form">
		<dt><%= f.label :name, "用户名"%></dt>
		<dd><%= f.text_field :name %></dd>
		<% if @user.errors[:name].any? %>
			<dd class="error"><%= @user.errors[:name][0]%></dd>
		<% end %>
	  </dl>
	  <dl class="form">
		<dt><%= f.label :email,"邮箱"%></dt>
		<dd><%= f.text_field :email%></dd>
		<% if @user.errors[:email].any? %>
			<dd class="error"><%= @user.errors[:email][0]%></dd>
		<% end %>
	  </dl>
	  <dl class="form">
		<dt><%= f.label :password, "密码"%></dt>
		<dd><%= f.password_field :password%></dd>
		<% if @user.errors[:password].any? %>
			<dd class="error"><%= @user.errors[:password][0]%></dd>
		<% end %>
	  </dl>
	  <dl class="form">
		<dt><%= f.label :password_confirmation,"确认密码"%></dt>
		<dd><%= f.password_field :password_confirmation %></dd>
		<% if @user.errors[:password_confirmation].any? %>
			<dd class="error"><%= @user.errors[:password_confirmation][0]%></dd>
		<% end %>
	  </dl>
	  <p><%= f.submit "注册", :class => "signup-button btn btn-primary" %></p>
	<% end %>
  </div>
</div>